name: Tests
on: [pull_request, workflow_dispatch]
jobs:
  collect-tests:
    outputs:
      test-files: ${{ steps.test-files.outputs.test-files }}
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Find test files
        id: test-files
        run: |
          cd tests
          export TESTS=$(ls */* | jq -R -s -c 'split("\n")[:-1]')
          echo "test-files=${TESTS}" >> $GITHUB_OUTPUT
  tests:
    needs: collect-tests
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJSON(needs.collect-tests.outputs.test-files) }}
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: install-kanata
        run: sudo apt-get update && sudo apt-get install -y kanata

      - name: run tests
        working-directory: tests
        run: kanata --check --cfg ${{ matrix.test }}

  tests-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: install-kanata
        run: brew install kanata

      - name: run tests
        run: kanata --check --cfg kanata.kbd

  tests-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: fetch kanata
        run: Invoke-WebRequest https://github.com/jtroo/kanata/releases/download/v1.12.0/windows-binaries-x64.zip -OutFile kanata.zip

      - name: unzip kanata
        run: unzip kanata.zip

      - name: run tests
        run: .\kanata_windows_tty_winIOv2_x64.exe --check --cfg kanata.kbd

  tests-older-versions:
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        kanata-release-link:
            # Pretty common version apparently
          - https://github.com/jtroo/kanata/releases/download/v1.8.0/kanata
            # Earliest release with the `--check` flag
          - https://github.com/jtroo/kanata/releases/download/v1.6.0/kanata
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: install-kanata
      run: wget ${{ matrix.kanata-release-link }} && chmod u+x kanata

    - name: run tests
      run: ./kanata --check
